#!/usr/bin/perl -w
use strict;
# 
# remove tutorial html links
#
for my $file ( @ARGV ) {
    print "processing $file.. ";
    my $fileText = `/bin/cat $file`;
    rename $file, "$file.bak";
    $fileText =~ s/^(\$tut = .*)instruct.*tutorial(\/gwtanline[^"].*)/# for information about tutorial cgi, contact the UMich repository owner\n# ${1}[local location of tutorial cgi]${2}/m;
    $fileText =~ s/^(\s*)("as shown.*)$/${1}"by using the derivative to find the slope of",\n\t"the tangent line and the point given.",\$esbox);\n# $1$2/m;
    open OF, ">$file";
    print OF $fileText;
#    print $fileText;
    close OF;
    print "done\n";
}
