#!/usr/bin/env perl

#use strict;
use File::Find;
use File::Basename;
use Cwd;
use DBI;

BEGIN {
        die "WEBWORK_ROOT not found in environment.\n"
                unless exists $ENV{WEBWORK_ROOT};
        # Unused variable, but define it to avoid an error message.
        $WeBWorK::Constants::WEBWORK_DIRECTORY = '';
}

use lib "$ENV{WEBWORK_ROOT}/lib";
use WeBWorK::CourseEnvironment;
use WeBWorK::Utils::Tags;

# Takes two paths, keeps the first, kills the second
# after copying its tags into the first file

my $keep = $ARGV[0];
my $kill = $ARGV[1];
my $keept = WeBWorK::Utils::Tags->new($keep);
my $killt = WeBWorK::Utils::Tags->new($kill);

if((not $keept->isplaceholder()) and (not $killt->isplaceholder())) {
    $keept->copyin($killt);
    $keept->write();

  if($keep =~ /^Library/) {
    $keep =~ s|^Library/||;
  }

open(OUF, ">$kill") or die "cannot open $kill";

print OUF <<"HERE";
# This file is just a pointer to the file
#
# "Library/$keep"
#
# You may want to change your problem set to use that problem
# directly, especially if you want to make a copy of the problem
# for modification.

DOCUMENT();
includePGproblem("Library/$keep");
ENDDOCUMENT();

## These tags keep this problem from being added to the NPL database
## 
## DBsubject('ZZZ-Inserted Text')
## DBchapter('ZZZ-Inserted Text')
## DBsection('ZZZ-Inserted Text')

HERE

close(OUF);
  } else {
    print "Did not change file $kill\n";
  }
