#!/usr/bin/env perl

# usage settags filename subject chapter section

#use strict;
use File::Find;
use File::Basename;
use DateTime;
use Cwd;

BEGIN {
        die "WEBWORK_ROOT not found in environment.\n"
                unless exists $ENV{WEBWORK_ROOT};
        # Unused variable, but define it to avoid an error message.
        $WeBWorK::Constants::WEBWORK_DIRECTORY = '';
}

use lib "$ENV{WEBWORK_ROOT}/lib";
use WeBWorK::CourseEnvironment;
use WeBWorK::Utils::Tags;

my $ce = new WeBWorK::CourseEnvironment({webwork_dir=>$ENV{WEBWORK_ROOT}});

my $libraryRoot = $ce->{problemLibrary}->{root};
$libraryRoot =~ s|/+$||;

die "Must have one argument, the file path" if (scalar(@ARGV) != 1);

my $fn = $ARGV[0];

my $cnt = 0;
my $nocnt=0;
my %vals = ();

my $tags = WeBWorK::Utils::Tags->new($fn);
$tags->{MO} = 1;
$tags->write();

print "Did $fn\n";

