#!/usr/bin/env perl

# usage settags filename subject chapter section

#use strict;
use File::Find;
use File::Basename;
use DateTime;
use Cwd;

BEGIN {
        die "WEBWORK_ROOT not found in environment.\n"
                unless exists $ENV{WEBWORK_ROOT};
        # Unused variable, but define it to avoid an error message.
        $WeBWorK::Constants::WEBWORK_DIRECTORY = '';
}

use lib "$ENV{WEBWORK_ROOT}/lib";
use WeBWorK::CourseEnvironment;
use WeBWorK::Utils::Tags;

my $ce = new WeBWorK::CourseEnvironment({webwork_dir=>$ENV{WEBWORK_ROOT}});

my $libraryRoot = $ce->{problemLibrary}->{root};
$libraryRoot =~ s|/+$||;

if (scalar(@ARGV) !=  4) {
  die "Must have 4 arguments: DBsubject DBchapter DBsection path";
}

my $fn = $ARGV[3];
my $subj = $ARGV[0];
my $chap = $ARGV[1];
my $sect = $ARGV[2];

my $cnt = 0;
my $nocnt=0;
my %vals = ();

my $tags = WeBWorK::Utils::Tags->new($fn);
$tags->{DBsubject} = $subj;
$tags->{DBchapter} = $chap;
$tags->{DBsection} = $sect;
$tags->write();

print "Did $fn\n";

