#!/usr/bin/perl

print <<'EOF'

This script has been replaced.  If your version of webwork
has the script .../webwork2/bin/NPL-update, then run that script
instead.  It does not require any command-line arguments, but
you do need to have the location of the problem library set in
global.conf.

If you do not have NPL-update, use loadDB2-deprecated in this
directory until you update your main version of webwork.

EOF
