#!/usr/bin/perl -w
use strict;
# 
# remove tutorial html links
#
for my $file ( @ARGV ) {
    print "processing $file.. ";
    my $fileText = `/bin/cat $file`;
    rename $file, "$file.bak";
    $fileText =~ s/^(\$tut = .*)instruct.math.lsa.*$/# for information about tutorial cgi, contact the UMich repository owner\n# ${1}[local location of tutorial cgi]" ./m;
    $fileText =~ s/^(\s+"gwderivtut[^"]*", ?")([^"]+)"/# $1$2/m;
    my $rule = $2;
    $fileText =~ s/^(SOLUTION.*)(", \$tut,)$/# $1$2\n$1$rule",/m;
    open OF, ">$file";
    print OF $fileText;
    close OF;
    print "done\n";
}
