#!/usr/bin/perl -w
use strict;
# 
# remove tutorial html links
#
for my $file ( @ARGV ) {
    print "processing $file.. ";
    my $fileText = `/bin/cat $file`;
    rename $file, "$file.bak";
    $fileText =~ s/^(\$tut = .*)instruct.*tutorial(\/gwinttut[^"]+",)(.+)(,.*)$/# for information about tutorial cgi, contact the UMich repository owner\n# ${1}[local location of tutorial cgi]${2}${3}${4}/m;
    my $rule = $3;
    $rule =~ s/^\s*//;
    $rule =~ s/\s*$//;
    $rule =~ s/^['"]//;
    $rule =~ s/['"]$//;
    $rule =~ s/"/'/g;
    $fileText =~ s/^(\s*)("by using \$tut)(.*)$/${1}"by using $rule$3\n# $1$2$3/m;
    $fileText =~ s/^##.*$//mg;
    $fileText =~ s/^\n\n\n$//mg;
    open OF, ">$file";
    print OF $fileText;
#    print $fileText;
    close OF;
    print "done\n";
}
